name: Validate code
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run Pre-Commit and linter
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      # https://github.com/marketplace/actions/engineerd-configurator
      - uses: engineerd/configurator@v0.0.10
        name: Setup helm
        with:
          name: helm
          url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
          pathInArchive: linux-amd64/helm
      - run: helm version

      # https://github.com/marketplace/actions/engineerd-configurator
      - uses: engineerd/configurator@v0.0.10
        name: Setup helm-docs
        with:
          name: helm-docs
          url: https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz
          pathInArchive: helm-docs
      - run: helm-docs --version

      - name: Helm Lint
        run: helm lint ./charts/* --strict

      - uses: pre-commit/action@v3.0.1
        name: Run pre-commit
        with:
          extra_args: --files charts/ethadapter/* charts/epi/* charts/fgt/* charts/quorum-node/* charts/couchdb/*

  checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      # https://github.com/bridgecrewio/checkov-action/tree/v12.1469.0
      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov smartcontract
        with:
          config_file: .checkov/smartcontract/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/smartcontract' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37

      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov ethadapter
        with:
          config_file: .checkov/ethadapter/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/ethadapter' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37

      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov epi
        with:
          config_file: .checkov/epi/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/epi' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37

      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov fgt
        with:
          config_file: .checkov/fgt/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/fgt' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37

      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov quorum-node-metrics-exporter
        with:
          config_file: .checkov/quorum-node-metrics-exporter/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/quorum-node-metrics-exporter' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37
